apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: wikijs
  namespace: wikijs
spec:
  hosts:
  - "*"
  gateways:
  - istio-system/gateway
  http:
  - match: 
    - uri:
        prefix: /
    route:
    - destination:
        host: wikijs
        port:
          number: 80